### ISSUE TITLE
Using a DB Adapter

### ISSUE THREAD

**Issue by ghost** [bauerca/drag-sort-listview#20]
Hey not really an issue, but I was wondering if you have an example of the Drag-Sort ListView implemented with an SQLite DB instead of an array. 

Specifically, I'm trying to add elements to the list on the fly and also store them in a DB.

Thank you so much for this extension of ListView. I wouldn't be surprised if Google builds this into Android.

Randy

**Comment by bauerca** [comment]
Hey Randy,

Thanks for the suggestion. I do have such an implementation in an app of mine, but it is not trivial and would take some work to turn into an example. I might just give it a go, since it would seem to be quite a common request.

Until then... Basically, I subclass a CursorAdapter and reorder the items obtained from the Cursor according to some saved index list (which gets updated as the user drag-sorts). Adding and storing items is mostly unrelated to DSLV. That is, if you update your DB and swap out your Cursor in your CursorAdapter, DSLV will notice just like ListView.

Cheers,
Carl

**Comment by ghost** [comment]
Thanks Carl,

I don't know why this is so hard for me, but I've been stuck on this for days.

I've got a working database where I can add entries with an EditText view and display all items in a ListView. But I can't get any of the drag and drop functionality to work. I've been trying to use your demos to figure it out, but it's just not the same using a SimpleCursorAdapter as it is using an Array Adapter.

I'll keep at it, but at this point any other details you can provide on how you got this working would be really helpful.

Thanks again!
Randy

**Comment by imminent** [comment]
I also need Drag and Dort on a `ListView` who's data is coming from a `CursorAdapter`. My idea is to use a `CursorWrapper` and swap in that `CursorWrapper` in the `onDrop` method. I have this (which seems to be working, at least visually):

``` java
private DragSortListView.DropListener _on_drop_listener =
                new DragSortListView.DropListener() {
                    @Override
                    public void drop(final int from, final int to) {
                        _adapter.swapCursor(new CursorWrapper(_adapter.getCursor()) {

                            @Override
                            public boolean moveToPosition(int position) {
                                if ((shift_down && position >= to && position <= from) ||
                                     (!shift_down && position <= to && position >= from))
                                    return super.moveToPosition(_remapping.get(position));
                                else
                                    return super.moveToPosition(position);
                            }

                            private final boolean shift_down = from > to;
                            private SparseIntArray _remapping = new SparseIntArray(Math.abs(from - to));

                            {
                                _remapping.put(from, to);
                                if (shift_down)
                                    for (int position = to; position < from; position++)
                                        _remapping.put(position, position + 1);
                                else // shift up
                                    for (int position = to; position > from; position--)
                                        _remapping.put(position, position - 1);
                            }
                        });
                    }
                };
```

I'm curious what your thoughts are on my approach.

**Comment by bauerca** [comment]
@imminent Nice! You could avoid object creation on every drop by subclassing CursorWrapper to do the reordering and just calling `notifyDataSetChanged()` on your adapter whenever a drop occurs, e.g.

```
private class MyCursor extends CursorWrapper implements DragSortListView.DropListener {
    @Override
    public void drop(int from, int to) {
        // update the SparseIntArray
        _adapter.notifyDataSetChanged();
    }

    @Override
    public boolean moveToPosition(int position) {
        // ...
    }
}
```

but that's probably a minor (if not moot) point. Thanks!

@Rlsl88 Just to be clear, is your problem that you can drag items around, but the drop does not perform the reordering? If so, the @imminent solution above should help you out.

**Comment by imminent** [comment]
Thanks @bauerca I changed the implementation:

``` java
private class ReorderCursor extends CursorWrapper implements DragSortListView.DropListener {

            ReorderCursor(Cursor cursor) {
                super(cursor);
                _remapping = new SparseIntArray();
            }

            @Override
             public void drop(int from, int to) {
                 // Update remapping
                 final int remapped_from = getRemappedPosition(from);
                 if (from > to)
                     for (int position = from; position > to; position--)
                         _remapping.put(position, getRemappedPosition(position - 1));
                 else // shift up
                     for (int position = from; position < to; position++)
                         _remapping.put(position, getRemappedPosition(position + 1)); 
                 _remapping.put(to, remapped_from);

                 _adapter.notifyDataSetChanged();
             }

            @Override
            public boolean moveToPosition(int position) {
                return super.moveToPosition(getRemappedPosition(position));
            }

            private int getRemappedPosition(int position) {
                return _remapping.get(position, position);
            }

            private final SparseIntArray _remapping;
        }
    }
```

I'm using a `CursorLoader`, so I create the `ReorderCursor` and wrap the `Cursor` in `onLoaderFinished`. And `setDropListener` the `ReorderCursor` after it's created.

**Comment by bauerca** [comment]
@imminent Nice solution. If only this were on StackOverflow, you could get some points! +1 from me...

@Rlsl88 I'm going to close this issue, since there is plenty to work from now. Feel free to keep commenting in this thread if you need more help.

**Comment by ghost** [comment]
Thanks guys!

Imminent, can you just explain how you are using the CursorLoader? I have my app set up to use  the deprecated "startManagingCursor()".

I think that might explain part of my trouble. 

If you have a working implementation of a DB and DSLV that you can share I'd really appreciate it. Hell, at this point, I'd pay you for it.

**Comment by imminent** [comment]
Okay, @Rlsl88 so `Activity`s and `Fragment`s have `LoaderManager` instances that you can get (through the support package for backward compatibility). Support `Fragment`s is through `getLoaderManager()`, `Activity`s use `getSupportLoaderManager()` I believe. The manager handles creating and, well, managing the `Loaders`, getting their events and passing it to the `LoaderManager.LoaderCallbacks` and dealing with the lifecycles (doing the right thing for the different `Activity` or `Fragment` lifecycles).

A `Loader` is is an `Object` that can start loading data of some form, and is basically always run on a background thread. `CursorLoader` (in the support package for backward compatibility) takes the `Context`, `Uri`, and other information about a `ContentProvider` query, then it performs that query asynchronously, and notfies the `LoaderManager` when it's done.

There are 3 callbacks in `LoaderManager`, `onCreateLoader`, `onLoadFinished`, and `onLoaderReset`. 

`onCreateLoader` is triggered by the `LoaderManager` when you are creating a `Loader` (and telling it to start loading data, in most cases, though it can be lacking the data to _really_ start loading data).

``` java
@Override
public Loader<Cursor> onCreateLoader(int loader_id, Bundle data) {
            final String[] projection = new String[] { "column_name1", "column_name2" };
            final String selection = "column_name1 = ?";
            final String[] selection_arguments = new String { "value1" };
            final String sort = "column_name2" + " ASC"
            return new CursorLoader(getActivity(), buildEmbeddedCalendarsDirUri(_model.getCalendar()), projection,
                                    selection, selection_arguments, sort);
}
```

`onLoadFinished` is triggered by the `Loader` when it has finished creating the data is it  returning. At this point you can now use the data (hence the asynchronous nature of `Loader`s). At this point you can swap in the Cursor into your `ListView`, which means you have already initialized the adapter (probably in the `onCreate` or `onViewCreated`). For DSLV, this is where you can attach the `ReorderCursor` (previously defined) as the `DropListener`. And the `LoaderManager` will register the `Loader` to watch the `Cursor` for changes.

``` java
@Override
public void onLoadFinished(Loader<Cursor> loader, Cursor cursor) {
            final ReorderCursor wrapped_cursor = new ReorderCursor(cursor);
            ((CursorAdapter) getListView().getAdapter()).swap(wrapped_cursor);
            ((DragSortListView) getListView()).setDropListener(wrapped_cursor);
}
```

`onLoaderReset` is triggered by the `Loader` when it is notified of content change in the `Cursor` (and thus needs to reload its content). @bauerca should we also set the `DropListener` to `null` here, as the `Cursor` will be closed by the `LoaderManager`?

``` java
@Override
public void onLoaderReset(Loader<Cursor> loader) {
            ((CursAdapter) getListView().getAdapter()).swap(null);
}
```

There are two methods you call to get things rolling (probably in `onCreate` or `onActivityCreated`):
1. `getLoaderManager().initLoader(int id, Bundle data, LoaderManager.LoaderCallbacks callbacks)` will check if the `LoaderManager` is already managing a `Loader` with the given id. If it is, then the `onLoadFinished` callback is executed on that `Loader` immediately, otherwise the `onCreateLoader` callback is performed and the `Loader` starts loading. You can manage multiple `Loader`s by changing the `id` and checking that `id` in the callbacks (and doing different things based on that `id`). `Loader.getId()` returns the `id` that was passed in the `onCreateLoader` execution that created the `Loader`. This might not be obvious, since the `LoaderManager` attaches the `id` for us. If you want to pass data to the `Loader` when you create it you can use the `Bundle` (you can see it is a parameter in `onCreateLoader`). This is useful, if you would like to use the data already loaded by the `Loader` if it already exists.
2. `getLoaderManager().resetLoader(int id, Bundle data, LoaderManager.LoaderCallbacks callbacks)` is similar to its counterpart, except it will force `onCreateLoader` in the case where the `LoaderManager` is already managing a `Loader` with the given `id`. This is useful where you want to make sure the `Loader` is using the data you're passing, as the `Loader` may be using a query that is different than what you're asking it to do now.

If you want to debug your `LoaderManager` callbacks call `LoaderManager.enableDebugLogging(true)` (preferably before you "get things rolling").

**Comment by bauerca** [comment]
@imminent Nice write-up. Regarding the DropListener: Probably doesn't matter either way, since a drag cannot be started if there are no items to drag. I do wonder what happens if the Cursor is swapped _while_ the user is dragging, though. Setting the DropListener to null would certainly avoid any resulting weird calls to `drop(from, to)`.

**Comment by imminent** [comment]
@bauerca, yeah, if it doesn't break DSLV to set the `DropListener` to `null` it might help avoid such weird cases.

**Comment by imminent** [comment]
@Rlsl88 @bauerca So I did more testing, it turns out I had my remapping logic backwards. My original test Cursor only had 2 items in it, because it's real data. The thing to note is, when I ask for position `x` where do I go in the `Cursor` to find the data. This is what the remapping is suppose to answer: when you ask for key `x` it returns position in the `Cursor` that should be currently displaying at position `x`. You actually want:

``` java
@Override
public void drop(int from, int to) {
     // Update remapping
     _remapping.put(to, from);
     if (from > to)
        for (int position = from; position > to; position--)
            _remapping.put(position, position - 1);
     else // shift up
        for (int position = from; position < to; position++)
            _remapping.put(position, position + 1);

     _adapter.notifyDataSetChanged();
}
```

I'm looking into the effect of multiple drap and drop actions, things might get more complicated.

**Comment by imminent** [comment]
Alright, here's what I have now, seems to work with multiple drag and drops in my testing:

``` java
@Override
public void drop(int from, int to) {
    // Update remapping
    final int remapped_from = getRemappedPosition(from);
    if (from > to)
        for (int position = from; position > to; position--)
            _remapping.put(position, getRemappedPosition(position - 1));
    else // shift up
        for (int position = from; position < to; position++)
            _remapping.put(position, getRemappedPosition(position + 1)); 
    _remapping.put(to, remapped_from);

    _adapter.notifyDataSetChanged();
}
```

I will update my original code too

**Comment by bauerca** [comment]
@Rlsl88 @imminent You should know that the DSLV library now contains some classes that will do the above for you. Check out the updated README and API docs for more. Thanks @imminent for the examples above, they helped me put DragSortCursorAdapter together.

-Carl

**Comment by imminent** [comment]
Awesome. Good work on the new implementation. I've been experimenting with
getting the native D and D framework to do ListView drag sort, because then
you could have  the code use the native framework when it exists. Have you
looked at their implementation? It's crazy entrenched into Android, and
uses a lot of native code. I don't think it's possible to get the same
performance without using the framework. That would be a good reason to use
it whenever you can. Then I believe with a tweak in the structure DSLV can
expose itself using the same interface as the framework, streamlining the
process of implementing the compatible drag and the native drag.

On Tuesday, October 30, 2012, Carl A. Bauer wrote:

> @Rlsl88 https://github.com/Rlsl88 @imminenthttps://github.com/imminentYou should know that the DSLV library now contains some classes that will
> do the above for you. Check out the updated README and API docs for more.
> Thanks @imminent https://github.com/imminent for the examples above,
> they helped me put DragSortCursorAdapter together.
> 
> -Carl
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/bauerca/drag-sort-listview/issues/20#issuecomment-9927696.

## 

## 

Dandré Allison                                (323) 823-4456
KeepandShare.com http://www.keepandshare.com
Group Sharing Made Easy & Secure

**Comment by bauerca** [comment]
You think performance will be that much better? Would be nice to run some tests.

I hesitate to use the D and D framework due to a few limitations.
1. The appearance of the DragShadow cannot be modified once you pass it to the framework (AFAIK). This is too bad b/c I imagine lots of fun effects on the floating View (the fade remove method is one; I think an explode remove would be cool, etc.).
2. The position of the DragShadow is always a fixed vector from the touch point. This is too bad b/c sometimes you want the floating View movement to be bounded. (See the Sections example in the demo project. Also, I think it's nice to restrict the floating View to the left-right ListView bounds when no fling remove is available; this indicates to the user that you cannot drag list items outside the ListView).

If we can find some clever way to enable these features in the D and D framework, I'm all for making the switch!

**Comment by orac** [comment]
Don't forget that D&D is only available from API level 11. A dependency on
the native D&D support would mean I'd have to fork, because my application
has to support API level 7 and up.
I still think native D&D integration, in a way that avoids these
difficulties,would be useful. As I've mentioned previously, I'd like to be
able to drag a DSLV item, and then if it gets dragged outside of the list
and native D&D is available, that starts a native drag so I can drag the
item into another View. Similarly, the reverse should be possible too: the
DSLV can be a drop target for a drag started elsewhere, so that when you
hover over the DSLV, the existing list items make a gap to drop it into,
and then the dropped item gets added in the correct position.
I certainly need to do something like this soon, so I'm happy to add this
myself, but I don't think it'll be until after Christmas if no one else
looks at it. I'm sure it's possible to do in such a way that the
integration works if native D&D is available, and has no effect otherwise.

**Comment by imminent** [comment]
Dan, it would be like how ActionBarSherlock uses the native ActionBar when
on devices that have those APIs while porting that functionality to older
devices. So support would not be lost.

Carl, I think you can do the swipe to remove, though I don't know how to do
it myself right now. I may have misread something but I have the impression
that you can modify the display of the DragShadow while dragging, like
alpha and color but maybe not make it a different view. I think the
framework documentation leaves much to be desired. I noticed the
implementation uses a lot of stuff that isn't publicly exposed with how the
events are sent and how it draws the DragShadow and stuff, that's why my
assumption is it will outperform a nonnative implementation.

**Comment by bauerca** [comment]
@orac Dragging items off of and on to DSLVs is something I'd like to see happen soon. I think an xml flag or something `use_native="true"` would be okay, with the understanding that, if enabled, bounds on dragging and floating View effects must be disabled. I do foresee some delicate issues, such as, what if a dev also wants the functionality demonstrated in the Sections demo?

@imminent I've tested and found that the system calls DragShadowBuilder.onDrawShadow/onProvideShadowMetrics only once. onDrawShadow provides a Canvas that you draw into, so the system is not holding onto a View and can't respond to invalidate()/requestLayout() and such. I guess you could hold onto the Canvas reference and try redrawing to it during a drag, but that behavior is undefined by Google and so I wouldn't trust it. onProvideShadowMetrics also supplies a Point object to set the touch offset on the DRagShadow, so one could hold onto the Point object and update it during drags to set bounds on the DragShadow, but, again, undefined -> untrustworthy. I think this is a big oversight on the part of the android devs.

**Comment by imminent** [comment]
So, @bauerca I noticed that the notification center does a swipe to remove notifications from the list that has a fade effect based on the position. I'm looking into the notification source code to see what they are using to do that, I found 

``` java
resetNotificationPeekFadeTimer()
```

in the `NotificationPeekPanel.java` so far, which sounds promising. You would probably have the sideways gesture go to the swipe to remove code, and the vertical dragging to go to the drag code. Once you're dragging an item, the only gesture that makes sense for removal is the throw gesture like they have in launcher and the home screen, so you might not need to change the display of the DragShadow (as it won't be a DragShadow, just a normal view on screen).
