### ISSUE TITLE
assumes every list item is a ViewGroup

### ISSUE THREAD

**Issue by orac** [bauerca/drag-sort-listview#30]
In several places, DragSortListView casts an item to ViewGroup without first checking with instanceof. Although it's usual that the items in a ListView are layouts, that's not always true. In my use case, each DSLV has a footer which is a Button. I get a ClassCastException when getItemHeights() tries to cast the Button to ViewGroup, on line 561.

As a workaround, if I wrap the Button in a FrameLayout, I get the correct behaviour.

**Comment by imminent** [comment]
DSLV wraps items in a RelativeLayout look at set Adapter(ListAdapter).
Which returns your views wrap inside a RelativeLayout. So unless you're
making views in the ListView outside of that they should probably be a
ViewGroup.

**Comment by orac** [comment]
Thanks for that pointer of where to look. When I examine the state in the debugger, I can see that mAdapter is a HeaderViewListAdapter wrapping the DSLV$AdapterWrapper. I think that what's happening is that since I've previously called addFooterView to add my footer, ListView sets up ListView.setAdapter to wrap the passed adapter in a HeaderViewListAdapter. When DSLV.setAdapter calls through to ListView.setAdapter, the AdapterWrapper gets further wrapped. When the HeaderViewListAdapter later creates its own view for my footer, it escapes being wrapped by the AdapterWrapper.
As your AdapterWrapper inherits HeaderViewListAdapter, it seems like the best thing would be to avoid ListView wrapping it again. Browsing the ListView code, it doesn't let you set a factory to make it create your own class instead of HeaderViewListAdapter, and it uses mHeaderViewInfos and mFooterViewInfos to decide whether to do the wrapping, so it might not be possible to avoid without overriding addHeaderView and addFooterView, and replicating all the code in there. That doesn't sound like a good way to fix it.

**Comment by imminent** [comment]
I'm not sure I follow all of that, but can you make your own AdapterWrapper
and extend DSLV to use yours?

**Comment by orac** [comment]
That wouldn't avoid ListView wrapping the adapter with its own HeaderViewListAdapter.

**Comment by bauerca** [comment]
Hey Dan,

This is indeed a bug. Thanks for noticing. The AdapterWrapper in DSLV does not wrap headers or footers, since DSLV considers headers/footers undraggable. My `getItemHeights` function assumes a normal wrapped item (in which case, the cast always works). However, I did not realize that DSLV might actually call `getItemHeights` on a header/footer (it can in `updatePositions()`). I will fix this shortly.

-Carl

**Comment by orac** [comment]
Thanks, that'll be great. I'd like to understand the code better, so I hope you don't mind if I ask what the need is to wrap everything in a RelativeLayout. Is it something to do with floating the views?

**Comment by mattiasbe** [comment]
That is the way extra space is "created" to be shown between rows during dragging. Emulating a drop point between rows.

**Comment by bauerca** [comment]
I need to wrap each item to provide the blank spot that tracks the floating View. The blank spot is created by expanding list items past their desired height. I can't expand a user-provided list item because the layout of its content will likely change.

This solution is a shortcut that comes with the cost of the extra layer in the View hierarchy. A laborious alternative would be to layout each list item myself; this basically amounts to a rewrite of ListView. Ugh.

**Comment by orac** [comment]
I see. Thanks for helping me understand.

**Comment by bauerca** [comment]
Well, this fix got me going on other optimizations; could be a bit before you see a commit. Until then, keep wrapping your Button in a FrameLayout. Thanks.
