### ISSUE TITLE
Support for pull to refresh

### ISSUE THREAD

**Issue by aliHafizji** [bauerca/drag-sort-listview#45]

**Comment by bauerca** [comment]
That would be nice. I think a new name would be needed. Maybe UltimateListView? :)

Pretty busy lately with $$-producing work; sorry for the late response. I have a few other features I'd like to add, then I'll look into this. Maybe some simple copy pasting from [this project](https://github.com/johannilsson/android-pulltorefresh) would do it.

**Comment by imminent** [comment]
@bauerca pretty soon you will have to rename the project is exactly what I was thinking :) The Android team will have to consider reimplementing ListView to be your ListView class.

**Comment by bauerca** [comment]
@aliHafizji If you need pull to refresh with drag-sort, I recommend modifying my project such that DragSortListView subclasses someone's PullToRefreshListView (or vice versa); the features should be mostly orthogonal. I'd rather not include this in dslv upstream, though, so that this project can focus on drag-sorting. Thanks!
