### ISSUE TITLE
setDragEnabled not working

### ISSUE THREAD

**Issue by aliHafizji** [bauerca/drag-sort-listview#56]
I don't know if I'm doing this right.

I used the drag-sort-listview in multi choice mode, and when the list enters multi choice mode I call setDragEnabled as false. Even then the drag initiates and the list item gets stuck.

Is it okay to setDragEnabled as false when multichoice mode is enabled? Am I missing something?

**Comment by bauerca** [comment]
This is a subtle bug. Thanks for finding it!

Even though dragEnabled=false, the DragSortController was still listening to touch events and calling DSLV.startDrag() when the right gesture was detected. The problem was that DSLV.startDrag() was ignoring the dragEnabled flag. This bug only occurs if the ListView consumes the touch event, which is why I wasn't seeing it in my demo project. Multichoice mode must cause touch event consumption by ListView.

I will close this issue when I commit the fix.

**Comment by bauerca** [comment]
Incidentally, #53 is addressing the issue of drag-sorting checkable items; which could give you the best of both worlds.

**Comment by bauerca** [comment]
Let me know if this doesn't fix the problem. Thanks.
