### ISSUE TITLE
Consolidate remove modes

### ISSUE THREAD

**Issue by bauerca** [bauerca/drag-sort-listview#64]
For those of you watching this repo, I'd like to get your opinion on a design decision I've been contemplating.

Currently, there are a gazillion remove modes and (with #61 in the works) I feel like the API is getting burdensome. In the spirit of making things easiest on the developer, I am proposing a consolidation (which necessarily removes some configurability).

The remove modes now (soon) are:
- click
- fling_left
- fling_right
- slide_left
- slide_right
- fling_or_slide (#61)

The middle 4 can happen while sorting. The last would be distinct from sorting.

I want to get rid of the middle 4. We would be left with:
- click
- fling

This looks sooooo much nicer to me, and seems more intuitive given the existing design patterns out there. (I mean, the left/right distinctions are just silly in my opinion). The new dslv operation would go like this (click remove would behave as usual):

If removeMode=fling, a side swipe _anywhere_ on the list item picks it up, locks it in the y direction (disabling sort). If a fling is not detected, it snaps back in place. This behavior mimics the android homescreen notification thingy. (caveat: if dragInitMode=onDown, the side swipe must not originate on the drag handle for a fling remove to be initiated. Otherwise a sort is initiated.) In all cases, a sort does not allow you to move the floating View left and right.

If there are any complaints to this proposed change, voice them here and as soon as you can. If the crickets begin to chirp, I'm gonna go ahead with these changes.

Thanks githubbers!
Carl

**Comment by imbryk** [comment]
So if anyone is interested in testing how exactly would this behave, then please take a look at the last commit in #61

**Comment by orac** [comment]
I think this is a great idea. This is the kind of thing I was hoping to start on the path of with my long-tap patch back in September. To get it really slick, I'd like to clear up what the fling option really does. Unless I've misunderstood you, I think you've mischaracterised the behaviour of the notification list. If you slowly slide an notification sideways, then it slides while y-locked as you say, and it fades out. But if you lift your finger with the notification slid more than halfway across, it slides the rest of the way on its own, regardless of the velocity when you lifted. I'd call that a "slide" rather than a "fling".

I hope I'm not just splitting hairs here: I think that the behaviour should mimic the notification list (and the "recent apps" list, which behaves the same way), I believe that's what you want too, and I want to make sure that that's what we all end up.

**Comment by imbryk** [comment]
You can do both on the notification (and recent apps) list - you can slowly slide sideways and lift your finger, or you can make a rapid short movement (i.e. "fling").
What I've done in my pull request is exactly this - pless try to compile the demo in the latest commit, and start "Basic usage playground", and write what you think.

**Comment by bauerca** [comment]
@orac how about "swipe"? :)

Sounds good. I'll take a look at your changes this weekend @imbryk

**Comment by samma835** [comment]
Hi, @bauerca . Thanks for the amazing project. I use it well and find a problem that can't be solved by myself. So here's my question:

How could I desensitize the fling(left and right). When I scroll the list(up and down), it's easy to trigger the fling (left and right). That's not my wanna.

Thanks and Wait for your reply.
