### ISSUE TITLE
DropListener doesn't work

### ISSUE THREAD

**Issue by boris-dev** [bauerca/drag-sort-listview#68]
1)getting DragSortListView

``` java
exerciseList = (DragSortListView) findViewById(R.id.lvEx);
```

2)setting adapter:

``` java
dragAdapter = new SimpleDragSortCursorAdapter(this,
            R.layout.exerciseslv, c, from, to,
            CursorAdapter.FLAG_REGISTER_CONTENT_OBSERVER);
exerciseList.setAdapter(dragAdapter);
```

3)setting DropListener:

``` java
        exerciseList.setDropListener(new DropListener() {
            @Override
            public void drop(int from, int to) {
                Log.i(LOG_TAG, "drop! from:" + from + " to: " + to);
            }
        });
```

4) trying to drag&drop, it sorts elements but i don't see log ("drop! from:").

thanks.

**Comment by bauerca** [comment]
The SimpleDragSortCursorAdapter implements the DropListener interface. `setAdapter()` calls `setDropListener()` if the given adapter is an instanceof DropListener. If you set the adapter _after_ you set your logging DropListener, the adapter object will be called. That's why you see reordering and no log. Otherwise you will see logging, but no reordering.

**Comment by boris-dev** [comment]
But I call setDropListener after setAdapter. I'm sure.

**Comment by bauerca** [comment]
That's weird. Is there _any_ way that setAdapter() would be called after setDropListener? (Like if you use setAdapter() to _reset_ the adapter on your dslv.)

**Comment by boris-dev** [comment]
yep, you are right, setAdapter calls in refresh function, that means it calls after setDropListener. Thank you)

**Comment by bauerca** [comment]
cool beans!
